# Transfer Learning:

In transfer learning, the knowledge of an already trained machine learning model is applied to a different but related problem. For example, if you trained a simple classifier to predict whether an image contains a watch, you could use the knowledge that the model gained during its training to recognize other objects like clock.


#### Pre trained model as Feature Extractor
Remove the last dense layer which is performing classification and use this pre trained model as Feature Extractor.Fixed feature extractor for the new dataset.

For example, if you want to build a self learning car. You can spend years to build a decent image recognition algorithm from scratch or you can take inception model (a pre-trained model) from Google which was built on ImageNet data to identify images in those pictures.


# Dataset Prepration 

In [1]:
import numpy as np
import tensorflow as tf

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os

dataset_path = os.listdir('dataset')

print (dataset_path)  #what kinds of classes are in this dataset

print("Types of classes labels found: ", len(dataset_path))

class_labels = []

for item in dataset_path:
 # Get all the file names
 all_classes = os.listdir('dataset' + '/' +item)
 #print(all_classes)

 # Add them to the list
 for room in all_classes:
    class_labels.append((item, str('dataset_path' + '/' +item) + '/' + room))
    #print(class_labels[:5])
    
    
# Build a dataframe        
df = pd.DataFrame(data=class_labels, columns=['Labels', 'image'])
print(df.head())
print(df.tail())

['foot-ulcers', 'Infected-necrotic-toes', 'leg-ulcer-images-venous-ulcer', 'pressure-ulcers-combine']
Types of classes labels found:  4
        Labels                                              image
0  foot-ulcers   dataset_path/foot-ulcers/309_0_foot-ulcer1-3.jpg
1  foot-ulcers  dataset_path/foot-ulcers/309_10_foot-ulcer1-3.jpg
2  foot-ulcers  dataset_path/foot-ulcers/309_11_foot-ulcer1-3.jpg
3  foot-ulcers  dataset_path/foot-ulcers/309_12_foot-ulcer1-3.jpg
4  foot-ulcers  dataset_path/foot-ulcers/309_13_foot-ulcer1-3.jpg
                       Labels  \
8037  pressure-ulcers-combine   
8038  pressure-ulcers-combine   
8039  pressure-ulcers-combine   
8040  pressure-ulcers-combine   
8041  pressure-ulcers-combine   

                                                  image  
8037  dataset_path/pressure-ulcers-combine/9_5_necro...  
8038  dataset_path/pressure-ulcers-combine/9_6_necro...  
8039  dataset_path/pressure-ulcers-combine/9_7_necro...  
8040  dataset_path/pressure-ulcers-co

In [2]:
# Let's check how many samples for each category are present
print("Total number of images in the dataset: ", len(df))

label_count = df['Labels'].value_counts()
print(label_count)

Total number of images in the dataset:  8042
pressure-ulcers-combine          3654
leg-ulcer-images-venous-ulcer    2835
foot-ulcers                      1008
Infected-necrotic-toes            545
Name: Labels, dtype: int64


In [3]:
import cv2
path = 'dataset/'
dataset_path = os.listdir('dataset')

im_size = 224

images = []
labels = []

for i in dataset_path:
    data_path = path + str(i)  
    filenames = [i for i in os.listdir(data_path) ]
   
    for f in filenames:
        img = cv2.imread(data_path + '/' + f)
        img = cv2.resize(img, (im_size, im_size))
        images.append(img)
        labels.append(i)

In [4]:

#This model takes input images of shape (224, 224, 3), and the input data should range [0, 255]. 

images = np.array(images)

images = images.astype('float32') / 255.0
images.shape

(8042, 224, 224, 3)

In [5]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
y=df['Labels'].values
print(y)

y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

['foot-ulcers' 'foot-ulcers' 'foot-ulcers' ... 'pressure-ulcers-combine'
 'pressure-ulcers-combine' 'pressure-ulcers-combine']
[1 1 1 ... 3 3 3]


In [6]:
np.unique(y)

array([0, 1, 2, 3])

In [7]:

y=y.reshape(-1,1)

from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('my_ohe', OneHotEncoder(), [0])], remainder='passthrough')
Y = ct.fit_transform(y) #.toarray()
print(Y[:5])
print(Y[35:])

  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (10, 1)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 1)	1.0
  (14, 1)	1.0
  (15, 1)	1.0
  (16, 1)	1.0
  (17, 1)	1.0
  (18, 1)	1.0
  (19, 1)	1.0
  (20, 1)	1.0
  (21, 1)	1.0
  (22, 1)	1.0
  (23, 1)	1.0
  (24, 1)	1.0
  :	:
  (7982, 3)	1.0
  (7983, 3)	1.0
  (7984, 3)	1.0
  (7985, 3)	1.0
  (7986, 3)	1.0
  (7987, 3)	1.0
  (7988, 3)	1.0
  (7989, 3)	1.0
  (7990, 3)	1.0
  (7991, 3)	1.0
  (7992, 3)	1.0
  (7993, 3)	1.0
  (7994, 3)	1.0
  (7995, 3)	1.0
  (7996, 3)	1.0
  (7997, 3)	1.0
  (7998, 3)	1.0
  (7999, 3)	1.0
  (8000, 3)	1.0
  (8001, 3)	1.0
  (8002, 3)	1.0
  (8003, 3)	1.0
  (8004, 3)	1.0
  (8005, 3)	1.0
  (8006, 3)	1.0


In [8]:
# Assuming y is a NumPy array
y = y.reshape(-1, 1)

# Apply one-hot encoding using ColumnTransformer
ct = ColumnTransformer([('my_ohe', OneHotEncoder(), [0])], remainder='passthrough')
Y = ct.fit_transform(y)

In [9]:
y

array([[1],
       [1],
       [1],
       ...,
       [3],
       [3],
       [3]])

In [10]:
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


images, Y = shuffle(images, Y, random_state=1)


train_x, test_x, train_y, test_y = train_test_split(images, Y, test_size=0.05, random_state=415)
#inpect the shape of the training and testing.
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)



(7639, 224, 224, 3)
(7639, 4)
(403, 224, 224, 3)
(403, 4)


train_y=train_y.toarray()
train_y = tf.constant(train_y, dtype=tf.float32)

## Transfer learning from pre-trained weights

#### Here we initialize the model with pre-trained ImageNet weights,and we fine-tune it on our own dataset.



The first step to transfer learning is to freeze all layers and train only the top layers. For this step, a relatively large learning rate (1e-2) can be used. 

EfficientNetB0(include_top=False, input_tensor=x, weights="imagenet")

include_top=False means we don't want to use classification layer(Dense from the pretrained network)

In [11]:
import cv2
import numpy as np
from matplotlib.pyplot import imread
from matplotlib.pyplot import imshow
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.imagenet_utils import decode_predictions
from tensorflow.keras.applications.imagenet_utils import preprocess_input
from tensorflow.keras import layers
from tensorflow.keras.applications import EfficientNetB0
import numpy as np
import tensorflow as tf

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os


NUM_CLASSES = 4
IMG_SIZE = 224



In [12]:
def build_model(num_classes):
    inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
    #x = img_augmentation(inputs)
    x = inputs
    model = EfficientNetB0(include_top=False, input_tensor=x, weights="imagenet")

    # Freeze the pretrained weights
    model.trainable = False

    # Rebuild top
    x = layers.GlobalAveragePooling2D(name="avg_pool")(model.output)
    x = layers.BatchNormalization()(x)

    top_dropout_rate = 0.2
    x = layers.Dropout(top_dropout_rate, name="top_dropout")(x)
    outputs = layers.Dense(NUM_CLASSES, activation="softmax", name="pred")(x)

    # Compile
    model = tf.keras.Model(inputs, outputs, name="EfficientNet")
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-2)
    model.compile(
        optimizer=optimizer, loss="sparse_categorical_crossentropy", metrics=["accuracy"]
    )
    return model

In [13]:

model = build_model(num_classes=NUM_CLASSES)

In [16]:
import matplotlib.pyplot as plt


def plot_hist(hist):
    plt.plot(hist.history["accuracy"])
    #plt.plot(hist.history["val_accuracy"])
    plt.title("model accuracy")
    plt.ylabel("accuracy")
    plt.xlabel("epoch")
    plt.legend(["train", "validation"], loc="upper left")
    plt.show()


#plot_hist(hist)


NameError: name 'sparse_tensor' is not defined

In [15]:
epochs = 2
hist = model.fit(train_x, train_y, epochs=epochs, verbose=2)

plot_hist(hist)

Epoch 1/2


TypeError: in user code:

    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1081, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1139, in compute_loss
        return self.compiled_loss(
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\losses.py", line 142, in __call__
        losses = call_fn(y_true, y_pred)
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\losses.py", line 268, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\losses.py", line 2354, in sparse_categorical_crossentropy
        return backend.sparse_categorical_crossentropy(
    File "C:\Users\Sifat Ullah\anaconda3\Lib\site-packages\keras\src\backend.py", line 5709, in sparse_categorical_crossentropy
        target = tf.convert_to_tensor(target)

    TypeError: Failed to convert elements of SparseTensor(indices=Tensor("DeserializeSparse:0", shape=(None, 2), dtype=int64), values=Tensor("DeserializeSparse:1", shape=(None,), dtype=float32), dense_shape=Tensor("stack:0", shape=(2,), dtype=int64)) to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.


In [ ]:
preds = model.evaluate(test_x, test_y)
print ("Loss = " + str(preds[0]))
print ("Test Accuracy = " + str(preds[1]))

In [ ]:
img_path = 'unseen.jfif'


img = cv2.imread(img_path)
img = cv2.resize(img, (224, 224))

x = np.expand_dims(img, axis=0)
x = preprocess_input(x)

print('Input image shape:', x.shape)

my_image = imread(img_path)
imshow(my_image)



preds=model.predict(x)
print("predicted class: ", preds )    # probabilities for being in each of the 3 classes